name: directme
description: An app to be used by care takers who handle patients.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^14.1.0
  flutter_native_splash: 
  flutter_svg: ^2.0.6
  firebase_auth: ^4.6.1
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  google_maps_flutter: 
  geofence_service: ^4.0.0
  geofence_flutter: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  cloud_firestore: ^4.8.0
  flutter_spinkit: ^5.2.0
  geolocator: ^9.0.2
  intl: ^0.18.1
  sliding_up_panel: ^2.0.0+1
  google_map_polyline_new: ^0.3.0+2
  google_maps_directions: ^0.0.3+4
  flutter_polyline_points: ^1.0.0
  speech_to_text: ^6.1.1
  http: ^0.13.6
  flutter_tts: ^3.7.0
  flutter_mapbox_autocomplete: ^2.0.0
  icons_launcher: ^2.1.2
  flutter_google_places: ^0.3.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 

icons_launcher:
  image_path: "assets/d.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
# splash screen
# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#D8D8D8"
  image: assets/d.png

  android_12:
    image: assets/d.png
    icon_background_color: "#F3F3F3"
  android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  ios_content_mode: center

  fullscreen: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
