// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIIUClw731TnLo1JLVZi_Yxw59l11g3b0',
    appId: '1:840165776707:android:216b45f8ab989acb2fe3f6',
    messagingSenderId: '840165776707',
    projectId: 'care-e9611',
    storageBucket: 'care-e9611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYnoDH981M_gkl8vYb_gQxpb0-9ZinMuA',
    appId: '1:840165776707:ios:d25f25827ffad64b2fe3f6',
    messagingSenderId: '840165776707',
    projectId: 'care-e9611',
    storageBucket: 'care-e9611.appspot.com',
    iosBundleId: 'com.example.careTaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYnoDH981M_gkl8vYb_gQxpb0-9ZinMuA',
    appId: '1:840165776707:ios:67aa0d483c7fcdac2fe3f6',
    messagingSenderId: '840165776707',
    projectId: 'care-e9611',
    storageBucket: 'care-e9611.appspot.com',
    iosBundleId: 'com.example.careTaker.RunnerTests',
  );
}
